#!/usr/bin/env python3
"""Import pinned icon geometry as native template SVG assets; never execute package JS.

Usage: python3 scripts/design/import-hugeicons.py /path/to/core-free-icons.tgz
Download the manifest's official tarball separately. Regenerates SVGs and Swift mapping.
"""
import hashlib
import json
import pathlib
import re
import sys
import tarfile
import xml.etree.ElementTree as ET

root = pathlib.Path(__file__).resolve().parents[2]
manifest = json.loads((root / "scripts/design/hugeicons-manifest.json").read_text())
archive = pathlib.Path(sys.argv[1])
assert hashlib.sha1(archive.read_bytes()).hexdigest() == manifest["sha1"], "Package checksum mismatch"
mapping = []
with tarfile.open(archive) as package:
    for icon in manifest["icons"]:
        source = package.extractfile(f'package/dist/esm/{icon["export"]}.js').read().decode()
        raw = re.search(r"const \w+ = (\[.*?\]);", source, re.S).group(1)
        raw = re.sub(r"([{,]\s*)([A-Za-z]\w*)\s*:", r'\1"\2":', raw)
        geometry = json.loads(raw)
        svg = ET.Element("svg", {"xmlns": "http://www.w3.org/2000/svg", "width": "24", "height": "24", "viewBox": "0 0 24 24", "fill": "none"})
        for tag, attributes in geometry:
            assert tag in {"path", "circle", "ellipse", "line", "rect", "polyline", "polygon"}
            converted = {}
            for key, value in attributes.items():
                if key == "key":
                    continue
                key = re.sub(r"([A-Z])", lambda m: "-" + m[1].lower(), key)
                converted[key] = "#000000" if value == "currentColor" else str(value)
            ET.SubElement(svg, tag, converted)
        directory = root / f'Check_Line/Assets.xcassets/{icon["asset"]}.imageset'
        directory.mkdir(parents=True, exist_ok=True)
        (directory / f'{icon["asset"]}.svg').write_text(ET.tostring(svg, encoding="unicode") + "\n")
        (directory / "Contents.json").write_text(json.dumps({"images": [{"filename": f'{icon["asset"]}.svg', "idiom": "universal"}], "info": {"author": "xcode", "version": 1}, "properties": {"preserves-vector-representation": True, "template-rendering-intent": "template"}}, indent=2) + "\n")
        mapping.extend((symbol, icon["asset"]) for symbol in icon["symbols"])
    license_text = package.extractfile("package/LICENSE.md").read().decode()
    (root / "Check_Line/Resources/ThirdPartyLicenses/Hugeicons-MIT.txt").write_text(license_text)
lines = ["import UIKit", "", "// Generated by scripts/design/import-hugeicons.py from the pinned MIT free pack.", "enum CheckLineIconAssets {", "    static let names: [String: String] = ["]
lines.extend(f'        "{symbol}": "{asset}",' for symbol, asset in sorted(mapping))
lines.extend(["    ]", "", "    static func templateImage(for symbol: String) -> UIImage {", "        let image = names[symbol].flatMap { UIImage(named: $0) } ?? UIImage(systemName: symbol)", "        return (image ?? UIImage()).withRenderingMode(.alwaysTemplate)", "    }", "}", ""])
(root / "Check_Line/DesignSystem/CheckLineIconAssets.swift").write_text("\n".join(lines))
print(f'Imported {len(manifest["icons"])} icons; {len(mapping)} display aliases. MIT license preserved.')
